# Generated by Django 5.2.6 on 2026-02-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المجلة')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='رابط فريد')),
                ('pdf_file', models.FileField(upload_to='magazines/pdfs/', verbose_name='ملف PDF')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='magazines/covers/', verbose_name='صورة الغلاف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مجلة',
                'verbose_name_plural': 'المجلات',
                'ordering': ['-created_at'],
            },
        ),
    ]
