# Generated by Django 5.2.6 on 2026-02-10 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazinePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='magazines/pages/')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.magazine')),
            ],
            options={
                'verbose_name': 'صفحة',
                'verbose_name_plural': 'صفحات المجلة',
                'ordering': ['page_number'],
            },
        ),
    ]
